<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbe04e9fae4708d4e3d15b72f71ef2da4
{
    public static $files = array (
        'b4e3f29b106af37a2bb239f73cdf68c7' => __DIR__ . '/../..' . '/app/helpers.php',
        'ccc005b63a9023e99a13de8faf57089e' => __DIR__ . '/../..' . '/packages/svea/phpintegration/src/Includes.php',
        '377bd8187c17b63752c3ef64f40d58c3' => __DIR__ . '/../..' . '/packages/nets/Includes.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'App\\AdTracking' => __DIR__ . '/../..' . '/app/AdTracking.php',
        'App\\CarData' => __DIR__ . '/../..' . '/app/CarData.php',
        'App\\CartCalculator' => __DIR__ . '/../..' . '/app/CartCalculator.php',
        'App\\Console\\Commands\\ReindexCommand' => __DIR__ . '/../..' . '/app/Console/Commands/ReindexCommand.php',
        'App\\Console\\Kernel' => __DIR__ . '/../..' . '/app/Console/Kernel.php',
        'App\\CronJobStatus' => __DIR__ . '/../..' . '/app/CronJobStatus.php',
        'App\\CustomerSearch' => __DIR__ . '/../..' . '/app/CustomerSearch.php',
        'App\\DeliveryMethod' => __DIR__ . '/../..' . '/app/DeliveryMethod.php',
        'App\\Exceptions\\Handler' => __DIR__ . '/../..' . '/app/Exceptions/Handler.php',
        'App\\Http\\Controllers\\AdminCMSController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminCMSController.php',
        'App\\Http\\Controllers\\AdminController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminController.php',
        'App\\Http\\Controllers\\AdminCustomerSearchesController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminCustomerSearchesController.php',
        'App\\Http\\Controllers\\AdminImagesController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminImagesController.php',
        'App\\Http\\Controllers\\AdminOrderCommentsController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminOrderCommentsController.php',
        'App\\Http\\Controllers\\AdminOrdersController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminOrdersController.php',
        'App\\Http\\Controllers\\AdminProductsController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminProductsController.php',
        'App\\Http\\Controllers\\AdminProfitController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminProfitController.php',
        'App\\Http\\Controllers\\AdminUsersController' => __DIR__ . '/../..' . '/app/Http/Controllers/AdminUsersController.php',
        'App\\Http\\Controllers\\Auth\\AuthController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/AuthController.php',
        'App\\Http\\Controllers\\Auth\\ForgotPasswordController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/ForgotPasswordController.php',
        'App\\Http\\Controllers\\Auth\\LoginController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/LoginController.php',
        'App\\Http\\Controllers\\Auth\\RegisterController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/RegisterController.php',
        'App\\Http\\Controllers\\Auth\\ResetPasswordController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/ResetPasswordController.php',
        'App\\Http\\Controllers\\CartController' => __DIR__ . '/../..' . '/app/Http/Controllers/CartController.php',
        'App\\Http\\Controllers\\CheckoutController' => __DIR__ . '/../..' . '/app/Http/Controllers/CheckoutController.php',
        'App\\Http\\Controllers\\Controller' => __DIR__ . '/../..' . '/app/Http/Controllers/Controller.php',
        'App\\Http\\Controllers\\CronJobController' => __DIR__ . '/../..' . '/app/Http/Controllers/CronJobController.php',
        'App\\Http\\Controllers\\EontyreApi' => __DIR__ . '/../..' . '/app/Http/Controllers/EontyreApi.php',
        'App\\Http\\Controllers\\InterSprint' => __DIR__ . '/../..' . '/app/Http/Controllers/InterSprint.php',
        'App\\Http\\Controllers\\PagesController' => __DIR__ . '/../..' . '/app/Http/Controllers/PagesController.php',
        'App\\Http\\Controllers\\SearchController' => __DIR__ . '/../..' . '/app/Http/Controllers/SearchController.php',
        'App\\Http\\Controllers\\UserController' => __DIR__ . '/../..' . '/app/Http/Controllers/UserController.php',
        'App\\Http\\Flash' => __DIR__ . '/../..' . '/app/Http/Flash.php',
        'App\\Http\\Kernel' => __DIR__ . '/../..' . '/app/Http/Kernel.php',
        'App\\Http\\Middleware\\Admin' => __DIR__ . '/../..' . '/app/Http/Middleware/Admin.php',
        'App\\Http\\Middleware\\EncryptCookies' => __DIR__ . '/../..' . '/app/Http/Middleware/EncryptCookies.php',
        'App\\Http\\Middleware\\RedirectIfAuthenticated' => __DIR__ . '/../..' . '/app/Http/Middleware/RedirectIfAuthenticated.php',
        'App\\Http\\Middleware\\VerifyCsrfToken' => __DIR__ . '/../..' . '/app/Http/Middleware/VerifyCsrfToken.php',
        'App\\Http\\Utilities\\Country' => __DIR__ . '/../..' . '/app/Http/Utilities/Country.php',
        'App\\Http\\Utilities\\UUID' => __DIR__ . '/../..' . '/app/Http/Utilities/UUID.php',
        'App\\Http\\Utilities\\WsseAuthHeader' => __DIR__ . '/../..' . '/app/Http/Utilities/WsseAuthHeader.php',
        'App\\Mail\\ConfirmOrderDenied' => __DIR__ . '/../..' . '/app/Mail/ConfirmOrderDenied.php',
        'App\\Mail\\ConfirmOrderSent' => __DIR__ . '/../..' . '/app/Mail/ConfirmOrderSent.php',
        'App\\Mail\\ConfirmOrderTreated' => __DIR__ . '/../..' . '/app/Mail/ConfirmOrderTreated.php',
        'App\\Mail\\ItemNotification' => __DIR__ . '/../..' . '/app/Mail/ItemNotification.php',
        'App\\Mail\\OrderConfirmation' => __DIR__ . '/../..' . '/app/Mail/OrderConfirmation.php',
        'App\\Mail\\OrderConfirmationCC' => __DIR__ . '/../..' . '/app/Mail/OrderConfirmationCC.php',
        'App\\Mail\\PaymentRejected' => __DIR__ . '/../..' . '/app/Mail/PaymentRejected.php',
        'App\\Mail\\Recite' => __DIR__ . '/../..' . '/app/Mail/Recite.php',
        'App\\Mail\\SendToFriend' => __DIR__ . '/../..' . '/app/Mail/SendToFriend.php',
        'App\\Mail\\SendUserPassword' => __DIR__ . '/../..' . '/app/Mail/SendUserPassword.php',
        'App\\Menu' => __DIR__ . '/../..' . '/app/Menu.php',
        'App\\Notifications\\ResetPassword' => __DIR__ . '/../..' . '/app/Notifications/ResetPassword.php',
        'App\\Order' => __DIR__ . '/../..' . '/app/Order.php',
        'App\\OrderComment' => __DIR__ . '/../..' . '/app/OrderComment.php',
        'App\\OrderDetail' => __DIR__ . '/../..' . '/app/OrderDetail.php',
        'App\\OrderStatus' => __DIR__ . '/../..' . '/app/OrderStatus.php',
        'App\\Page' => __DIR__ . '/../..' . '/app/Page.php',
        'App\\PaymentMethod' => __DIR__ . '/../..' . '/app/PaymentMethod.php',
        'App\\Product' => __DIR__ . '/../..' . '/app/Product.php',
        'App\\ProductImage' => __DIR__ . '/../..' . '/app/ProductImage.php',
        'App\\ProductType' => __DIR__ . '/../..' . '/app/ProductType.php',
        'App\\Profit' => __DIR__ . '/../..' . '/app/Profit.php',
        'App\\Providers\\AppServiceProvider' => __DIR__ . '/../..' . '/app/Providers/AppServiceProvider.php',
        'App\\Providers\\AuthServiceProvider' => __DIR__ . '/../..' . '/app/Providers/AuthServiceProvider.php',
        'App\\Providers\\BroadcastServiceProvider' => __DIR__ . '/../..' . '/app/Providers/BroadcastServiceProvider.php',
        'App\\Providers\\EventServiceProvider' => __DIR__ . '/../..' . '/app/Providers/EventServiceProvider.php',
        'App\\Providers\\RouteServiceProvider' => __DIR__ . '/../..' . '/app/Providers/RouteServiceProvider.php',
        'App\\Repositories\\Products\\ElasticsearchProductsRepository' => __DIR__ . '/../..' . '/app/Repositories/Products/ElasticsearchProductsRepository.php',
        'App\\Repositories\\Products\\EloquentProductsRepository' => __DIR__ . '/../..' . '/app/Repositories/Products/EloquentProductsRepository.php',
        'App\\Repositories\\Products\\ProductsRepository' => __DIR__ . '/../..' . '/app/Repositories/Products/ProductsRepository.php',
        'App\\Search\\ElasticsearchObserver' => __DIR__ . '/../..' . '/app/Search/ElasticsearchObserver.php',
        'App\\Search\\Searchable' => __DIR__ . '/../..' . '/app/Search/Searchable.php',
        'App\\Setting' => __DIR__ . '/../..' . '/app/Setting.php',
        'App\\ShippingCost' => __DIR__ . '/../..' . '/app/ShippingCost.php',
        'App\\Slider' => __DIR__ . '/../..' . '/app/Slider.php',
        'App\\Supplier' => __DIR__ . '/../..' . '/app/Supplier.php',
        'App\\UpstepsTmp' => __DIR__ . '/../..' . '/app/UpstepsTmp.php',
        'App\\User' => __DIR__ . '/../..' . '/app/User.php',
        'App\\UserType' => __DIR__ . '/../..' . '/app/UserType.php',
        'CreateAdTrackingsTable' => __DIR__ . '/../..' . '/database/migrations/2017_12_07_131135_create_ad_trackings_table.php',
        'CreateCarDataTable' => __DIR__ . '/../..' . '/database/migrations/2016_09_13_083006_create_car_data_table.php',
        'CreateCronJobStatusTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_14_123816_create_cron_job_status_table.php',
        'CreateCustomerSearchesTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_17_073117_create_customer_searches_table.php',
        'CreateDeliveryMethodsTable' => __DIR__ . '/../..' . '/database/migrations/2017_01_03_124137_create_delivery_methods_table.php',
        'CreateMenuPageTable' => __DIR__ . '/../..' . '/database/migrations/2017_07_11_160950_create_menu_page_table.php',
        'CreateMenusTable' => __DIR__ . '/../..' . '/database/migrations/2017_07_11_160618_create_menus_table.php',
        'CreateOrderCommentsTable' => __DIR__ . '/../..' . '/database/migrations/2016_12_01_143947_create_order_comments_table.php',
        'CreateOrderDetailsTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_121913_create_order_details_table.php',
        'CreateOrderStatusTable' => __DIR__ . '/../..' . '/database/migrations/2016_06_06_121029_create_order_status_table.php',
        'CreateOrdersTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_122941_create_orders_table.php',
        'CreatePagesTable' => __DIR__ . '/../..' . '/database/migrations/2017_07_10_153315_create_pages_table.php',
        'CreatePasswordResetsTable' => __DIR__ . '/../..' . '/database/migrations/2014_10_12_100000_create_password_resets_table.php',
        'CreatePaymentMethodsTable' => __DIR__ . '/../..' . '/database/migrations/2017_02_01_105237_create_payment_methods_table.php',
        'CreatePaymentsTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_004749_create_payments_table.php',
        'CreateProductCategoriesTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_071715_create_product_categories_table.php',
        'CreateProductImagesTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_132930_create_product_images_table.php',
        'CreateProductTypeTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_074821_create_product_type_table.php',
        'CreateProductsTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_084448_create_products_table.php',
        'CreateProfitTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_075626_create_profit_table.php',
        'CreateSettingsTable' => __DIR__ . '/../..' . '/database/migrations/2017_07_22_123622_create_settings_table.php',
        'CreateShippersTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_003728_create_shippers_table.php',
        'CreateShippingCostTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_05_121052_create_shipping_cost_table.php',
        'CreateSlidersTable' => __DIR__ . '/../..' . '/database/migrations/2017_07_17_122408_create_sliders_table.php',
        'CreateSuppliersTable' => __DIR__ . '/../..' . '/database/migrations/2016_07_04_075340_create_suppliers_table.php',
        'CreateUpstepsTmpTable' => __DIR__ . '/../..' . '/database/migrations/2017_02_14_074308_create_upsteps_tmp_table.php',
        'CreateUserTypeTable' => __DIR__ . '/../..' . '/database/migrations/2016_09_07_121319_create_user_type_table.php',
        'CreateUsersTable' => __DIR__ . '/../..' . '/database/migrations/2014_10_12_000000_create_users_table.php',
        'DatabaseSeeder' => __DIR__ . '/../..' . '/database/seeds/DatabaseSeeder.php',
        'DeliveryMethodsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/DeliveryMethodsTableSeeder.php',
        'MenusTableSeeder' => __DIR__ . '/../..' . '/database/seeds/MenusTableSeeder.php',
        'OrderDetailTableSeeder' => __DIR__ . '/../..' . '/database/seeds/OrderDetailTableSeeder.php',
        'OrderStatusTableSeeder' => __DIR__ . '/../..' . '/database/seeds/OrderStatusTableSeeder.php',
        'OrderTableSeeder' => __DIR__ . '/../..' . '/database/seeds/OrderTableSeeder.php',
        'PagesTableSeeder' => __DIR__ . '/../..' . '/database/seeds/PagesTableSeeder.php',
        'PaymentMethodsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/PaymentMethodsTableSeeder.php',
        'PaymentsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/PaymentsTableSeeder.php',
        'ProductCategoriesTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ProductCategoriesTableSeeder.php',
        'ProductImagesTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ProductImagesTableSeeder.php',
        'ProductTypeTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ProductTypeTableSeeder.php',
        'ProductsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ProductsTableSeeder.php',
        'ProfitsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ProfitsTableSeeder.php',
        'SettingsTableSeeder' => __DIR__ . '/../..' . '/database/seeds/SettingsTableSeeder.php',
        'ShippingCostTableSeeder' => __DIR__ . '/../..' . '/database/seeds/ShippingCostTableSeeder.php',
        'SuppliersTableSeeder' => __DIR__ . '/../..' . '/database/seeds/SuppliersTableSeeder.php',
        'Tests\\TestCase' => __DIR__ . '/../..' . '/tests/TestCase.php',
        'UserTypeTableSeeder' => __DIR__ . '/../..' . '/database/seeds/UserTypeTableSeeder.php',
        'UsersTableSeeder' => __DIR__ . '/../..' . '/database/seeds/UsersTableSeeder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbe04e9fae4708d4e3d15b72f71ef2da4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbe04e9fae4708d4e3d15b72f71ef2da4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbe04e9fae4708d4e3d15b72f71ef2da4::$classMap;

        }, null, ClassLoader::class);
    }
}
